SET ROLE appuser;

BEGIN;

CREATE TABLE IF NOT EXISTS public.symbol_master
(
    symbol_id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source                 TEXT        NOT NULL,
    market                 TEXT        NOT NULL,
    category               TEXT        NOT NULL,
    symbol                 TEXT        NOT NULL,
    name                   TEXT        NOT NULL,
    source_code            TEXT,
    market_type            TEXT,
    interval_type          TEXT        NOT NULL DEFAULT '1m',
    chart_range            TEXT        NOT NULL DEFAULT '1d',
    recent_candle_count    INTEGER     NOT NULL DEFAULT 15,
    collection_enabled     BOOLEAN     NOT NULL DEFAULT true,
    collection_priority    INTEGER     NOT NULL DEFAULT 100,
    held_in_account        BOOLEAN     NOT NULL DEFAULT false,
    managed_by_holdings    BOOLEAN     NOT NULL DEFAULT false,
    description            TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT symbol_master_pk
        PRIMARY KEY (symbol_id),

    CONSTRAINT symbol_master_source_symbol_uk
        UNIQUE (source, symbol)
);

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS source TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS market TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS category TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS symbol TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS source_code TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS market_type TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS interval_type TEXT DEFAULT '1m';

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS chart_range TEXT DEFAULT '1d';

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS recent_candle_count INTEGER DEFAULT 15;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS collection_enabled BOOLEAN DEFAULT true;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS collection_priority INTEGER DEFAULT 100;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS held_in_account BOOLEAN DEFAULT false;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS managed_by_holdings BOOLEAN DEFAULT false;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

ALTER TABLE public.symbol_master
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

UPDATE public.symbol_master
SET
    interval_type       = COALESCE(interval_type, '1m'),
    chart_range         = COALESCE(chart_range, '1d'),
    recent_candle_count = COALESCE(recent_candle_count, 15),
    collection_enabled  = COALESCE(collection_enabled, true),
    collection_priority = COALESCE(collection_priority, 100),
    held_in_account      = COALESCE(held_in_account, false),
    managed_by_holdings  = COALESCE(managed_by_holdings, false),
    created_at          = COALESCE(created_at, now()),
    updated_at          = COALESCE(updated_at, now());

ALTER TABLE public.symbol_master
    ALTER COLUMN interval_type SET DEFAULT '1m',
    ALTER COLUMN chart_range SET DEFAULT '1d',
    ALTER COLUMN recent_candle_count SET DEFAULT 15,
    ALTER COLUMN collection_enabled SET DEFAULT true,
    ALTER COLUMN collection_priority SET DEFAULT 100,
    ALTER COLUMN held_in_account SET DEFAULT false,
    ALTER COLUMN managed_by_holdings SET DEFAULT false,
    ALTER COLUMN created_at SET DEFAULT now(),
    ALTER COLUMN updated_at SET DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS symbol_master_source_symbol_uk_idx
    ON public.symbol_master
    (
        source,
        symbol
    );

CREATE UNIQUE INDEX IF NOT EXISTS symbol_master_toss_source_code_uk
    ON public.symbol_master
    (
        source,
        source_code
    )
    WHERE source = 'TOSS'
      AND source_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_symbol_master_collection
    ON public.symbol_master
    (
        source,
        collection_enabled,
        collection_priority,
        symbol_id
    );

INSERT INTO public.symbol_master
(
    source,
    market,
    category,
    symbol,
    name,
    source_code,
    market_type,
    interval_type,
    chart_range,
    recent_candle_count,
    collection_enabled,
    collection_priority,
    description
)
VALUES
(
    'TOSS',
    'KR',
    'STOCK',
    'A005930',
    'Samsung Electronics',
    '005930',
    'kr-s',
    '1m',
    'day',
    21,
    true,
    10,
    'Toss Invest KR stock'
),
(
    'TOSS',
    'KR',
    'STOCK',
    'A000660',
    'SK Hynix',
    '000660',
    'kr-s',
    '1m',
    'day',
    21,
    true,
    20,
    'Toss Invest KR stock'
),
(
    'YAHOO',
    'US',
    'INDEX',
    '^IXIC',
    'NASDAQ Composite',
    '^IXIC',
    NULL,
    '1m',
    '1d',
    15,
    true,
    100,
    'NASDAQ Composite Index'
),
(
    'YAHOO',
    'US',
    'INDEX',
    '^GSPC',
    'S and P 500',
    '^GSPC',
    NULL,
    '1m',
    '1d',
    15,
    true,
    110,
    'S and P 500 Index'
),
(
    'YAHOO',
    'US',
    'VOLATILITY',
    '^VIX',
    'VIX',
    '^VIX',
    NULL,
    '1m',
    '1d',
    15,
    true,
    120,
    'CBOE Volatility Index'
),
(
    'YAHOO',
    'US',
    'FUTURES',
    'NQ=F',
    'NASDAQ 100 Futures',
    'NQ=F',
    NULL,
    '1m',
    '1d',
    15,
    true,
    130,
    'NASDAQ 100 Futures'
),
(
    'YAHOO',
    'US',
    'INDEX',
    '^DJI',
    'Dow Jones Industrial Average',
    '^DJI',
    NULL,
    '1m',
    '1d',
    15,
    true,
    140,
    'Dow Jones Industrial Average'
),
(
    'YAHOO',
    'KR',
    'INDEX',
    '^KS11',
    'KOSPI',
    '^KS11',
    NULL,
    '1m',
    '1d',
    15,
    true,
    150,
    'KOSPI Index'
),
(
    'YAHOO',
    'US',
    'INDEX',
    '^SOX',
    'Philadelphia Semiconductor Index',
    '^SOX',
    NULL,
    '1m',
    '1d',
    15,
    true,
    160,
    'Philadelphia Semiconductor Index'
),
(
    'YAHOO',
    'US',
    'BOND_YIELD',
    '^TNX',
    'US 10 Year Treasury Yield',
    '^TNX',
    NULL,
    '1m',
    '1d',
    15,
    true,
    170,
    'US 10 Year Treasury Yield'
),
(
    'YAHOO',
    'GLOBAL',
    'COMMODITY',
    'GC=F',
    'Gold Futures',
    'GC=F',
    NULL,
    '1m',
    '1d',
    15,
    true,
    180,
    'Gold Futures'
),
(
    'YAHOO',
    'GLOBAL',
    'COMMODITY',
    'CL=F',
    'WTI Crude Oil Futures',
    'CL=F',
    NULL,
    '1m',
    '1d',
    15,
    true,
    190,
    'WTI Crude Oil Futures'
),
(
    'YAHOO',
    'GLOBAL',
    'COMMODITY',
    'BZ=F',
    'Brent Crude Oil Futures',
    'BZ=F',
    NULL,
    '1m',
    '1d',
    15,
    true,
    200,
    'Brent Crude Oil Futures'
),
(
    'YAHOO',
    'KR',
    'FX',
    'KRW=X',
    'USD KRW',
    'KRW=X',
    NULL,
    '1m',
    '1d',
    15,
    true,
    210,
    'US Dollar to Korean Won'
),
(
    'YAHOO',
    'GLOBAL',
    'CRYPTO',
    'BTC-USD',
    'Bitcoin',
    'BTC-USD',
    NULL,
    '1m',
    '1d',
    15,
    true,
    220,
    'Bitcoin USD'
),
(
    'YAHOO',
    'GLOBAL',
    'CRYPTO',
    'ETH-USD',
    'Ethereum',
    'ETH-USD',
    NULL,
    '1m',
    '1d',
    15,
    true,
    230,
    'Ethereum USD'
)
ON CONFLICT (source, symbol)
DO UPDATE
SET
    market                 = EXCLUDED.market,
    category               = EXCLUDED.category,
    name                   = EXCLUDED.name,
    source_code            = EXCLUDED.source_code,
    market_type            = EXCLUDED.market_type,
    interval_type          = EXCLUDED.interval_type,
    chart_range            = EXCLUDED.chart_range,
    recent_candle_count    = EXCLUDED.recent_candle_count,
    collection_enabled     = EXCLUDED.collection_enabled,
    collection_priority    = EXCLUDED.collection_priority,
    description            = EXCLUDED.description,
    updated_at             = now();

COMMIT;
